name: Sync to Gitee

on:
  push:
    branches: [ main ]  # 当你向 main 分支推送代码时触发
  release:
    types: [published]  # 当你发布新 Release 时触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to Gitee
        uses: NEVSTOP-LAB/GitHub-Gitee-Sync@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          gitee-token: ${{ secrets.GITEE_TOKEN }}
          gitee-owner: ${{ secrets.GITEE_OWNER }}
          # 明确指定只同步 Exero 仓库，并同步 Releases
          include-repos: 'Exero'
          sync-extra: 'releases'
